print("-------- MY PROFILE --------")

name = input("Enter your name: ")
college = input("Enter your college name: ")
course = input("Enter your course: ")
company = input("Enter your dream company: ")
language = input("Enter your favorite programming language: ")
city = input("Enter your city: ")
cgpa = float(input("Enter your CGPA: "))

print("\n-------- MY PROFILE --------")
print("Name :", name)
print("College :", college)
print("Course :", course)
print("Dream Company :", company)
print("Favorite Language :", language)
print("City :", city)
print("CGPA :", cgpa)
print("----------------------------")